### ISSUE TITLE
Widget Body

### ISSUE THREAD

**Issue by overload08** [domogik/domoweb#105]
Dans la console de Chrome : 
Failed to load resource: the server responded with a status of 404 (Not Found) http://10.0.101.25:40404/widget/health/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0
Failed to load resource: the server responded with a status of 404 (Not Found) 
http://10.0.101.25:40404/widget/health/font-awesome-4.7.0/fonts/fontawesome-webfont.woff?v=4.7.0 
Failed to load resource: the server responded with a status of 404 (Not Found) 
http://10.0.101.25:40404/widget/health/font-awesome-4.7.0/fonts/fontawesome-webfont.woff?v=4.7.0

**Comment by fritz-smh** [comment]
Fixed
