### ISSUE TITLE
Widget "command Boolean" transformation flèche en main

### ISSUE THREAD

**Issue by FrancoisGin28** [domogik/domoweb#112]
Bonjour

Au passage de la souris sur un widget "command Boolean" le flèche de souris ne se transforme pas en main ....

merci d'avance !!

**Comment by overload08** [comment]
Patch : 


--- basicCommand.html.old       2017-01-18 19:50:39.902495864 +0100
+++ basicCommand.html   2017-01-18 19:50:00.790497418 +0100
@@ -12,6 +12,7 @@
                 height: 80%;
                 margin: 10%;
                 color: #000000;
+               cursor: pointer;
             }
             button#send.circle {
                 border-radius: 50%;

**Comment by FrancoisGin28** [comment]
Merci Overload pour le patch ... mais je ne trouve pas le fichier basicCommand.html ....

**Comment by overload08** [comment]
C'est le fichier /opt/dmg/domoweb/packs/widgets/basic/commandTrigger.html qu'il faut patcher

**Comment by FrancoisGin28** [comment]
voici mon fichier 

<polymer-element name="dmw-basic-commandTrigger" extends="dmw-widget">
    <template>
        <link rel="stylesheet" href="/widget/basic/css/common.css" shim-domshadow>
        <style type="text/css">
            :host {
                height: 100%;
            }
            button#send {
                display: block;
                border-style: none;
                width: 80%;
                height: 80%;
                margin: 10%;
                background: #4671BD;
                color: #ffffff;
                cursor: pointer;
            }
            button#send.circle {
                border-radius: 50%;
            }
            button#send:active {
                background: #D73032;
                color: #ffffff;
            }
        </style>
        <dmw-command id="primary" commandkey="primary"></dmw-command>
        <shadow></shadow>
        <button id="send" class="btn btn-default">{{sendtext}}</button>
    </template>
    <script>
        Polymer('dmw-basic-commandTrigger', {
            ready: function() {
                this.super();
            },
            optionsUpdated: function() {
                if (this.options['hideLabels'] == true ) {         
                    this.$.labelprimary.style.visibility = "hidden";
                    this.$.labelsecondary.style.visibility = "hidden";
                }
                else {
                    this.$.labelprimary.style.visibility = "visible";
                    this.$.labelsecondary.style.visibility = "visible";
                }
            },
            commandsUpdated: function() {
                if (this.$.primary.isSet) {
                    this.labelprimary = this.$.primary.device['name'];
                    this.labelsecondary = this.$.primary.name;
                    if ((this.options['label'] != undefined) && (this.options['label'] != "")) {
                        this.sendtext = this.options['label'];
                    }
                    else {
                        this.sendtext = i18n.t("basic:trigger");
                    }
                    this.$.send.addEventListener('click', this.send.bind(this));
                }
                if (this.options['circle'] == 1) {
                    this.$.send.classList.add('circle');
                }
                if (this.options['circle'] == 0) {
                    this.$.send.classList.remove('circle');
                }
            },
            send: function(e) {
                var parameters = {};
                parameters[this.$.primary.parameters[0]['key']] = 1;
                this.$.primary.send(parameters);
                e.preventDefault();
                e.stopPropagation();
            }
        });
    </script>
</polymer-element>

**Comment by overload08** [comment]
Punaise le c**... c'est pas /opt/dmg/domoweb/packs/widgets/basic/commandTrigger.html mais /opt/dmg/domoweb/packs/widgets/basic/commandBool.html !

**Comment by overload08** [comment]
Remplace : 
```
            button#send {
                display: block;
                border-style: none;
                width: 80%;
                height: 80%;
                margin: 10%;
                color: #000000;
            }
```
Par : 
```
            button#send {
                display: block;
                border-style: none;
                width: 80%;
                height: 80%;
                margin: 10%;
                color: #000000;
                cursor: pointer;
            }
```

**Comment by FrancoisGin28** [comment]
Bonsoir,
Et bien modification faites mais pas de changement ....

merci d'avance
Francois

**Comment by overload08** [comment]
Vide ton cache du navigateur.

-------- Message original --------
Objet : Re: [domogik/domoweb] Widget "command Boolean" transformation flèche en main (#112)
De : FrancoisGin28
À : domogik/domoweb
Cc : overload08 ,Comment


Bonsoir,
Et bien modification faites mais pas de changement ....

merci d'avance
Francois

**Comment by fritz-smh** [comment]
Passer en navigation privée est pratique également pour les tests :)

**Comment by FrancoisGin28** [comment]
Merci c'est OK ... je suis rouge de honte coté cache .... 

Tout est bon !!

**Comment by overload08** [comment]
Pas grave, ça m'arrive aussi ;)
Garde le ticket ouvert pour que les dev merge la modif

-------- Message original --------
Objet : Re: [domogik/domoweb] Widget "command Boolean" transformation flèche en main (#112)
De : FrancoisGin28
À : domogik/domoweb
Cc : overload08 ,Comment


Merci c'est OK ... je suis rouge de honte coté cache ....

Tout est bon !!
