### ISSUE TITLE
Trigger widget issue

### ISSUE THREAD

**Issue by overload08** [domogik/domoweb#113]
When i click on tigger button : 

```
[I 170118 15:19:23 handlers:201] WS: Received message ["command-send",{"command_id":85,"parameters":{"current":1},"rest_auth":{"username":"***","password":"***"}}]
[E 170118 15:19:33 concurrent:129] Future exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 285, in wrapper
        yielded = next(result)
      File "/opt/dmg/domoweb/domoweb/handlers.py", line 228, in on_message
        }[jsonmessage[0]](jsonmessage[1])
      File "/opt/dmg/domoweb/domoweb/handlers.py", line 350, in WSCommandSend
        return cli.request('xplgw', msg.get(), timeout=10).get()
    AttributeError: 'NoneType' object has no attribute 'get'
```

I don't know if it's my plugin that do that or if it's a domoweb bug

**Comment by tikismoke** [comment]
Same here with working widgets in the past.
No relation to any plugins (ozwave/vdevice/plcbus) non works:

`[I 170121 14:32:28 handlers:201] WS: Received message ["command-send",{"command_id":178,"parameters":{"value":0},"rest_auth":{"username":"admin","password":"123"}}]
[E 170121 14:32:38 concurrent:124] Future exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/home/domoweb/domoweb/handlers.py", line 228, in on_message
        }[jsonmessage[0]](jsonmessage[1])
      File "/home/domoweb/domoweb/handlers.py", line 350, in WSCommandSend
        return cli.request('xplgw', msg.get(), timeout=10).get()
    AttributeError: 'NoneType' object has no attribute 'get'
`

**Comment by tikismoke** [comment]
Ha sorry indeed only VDEVICE seems to not works, ozwave and plcbus are ok.

**Comment by overload08** [comment]
Do you know why ?

**Comment by tikismoke** [comment]
Absolutely not :(

**Comment by overload08** [comment]
Plugin doesn't catch command, not related to DMW

**Comment by tikismoke** [comment]
>  2017-02-02 19:54:25,052 domogik-vdevice INFO ==> Received 0MQ messages data: {u'command_id': 178, u'value': 1, u'device_id': 245}
> <tikismoke> 2017-02-02 19:54:25,052 domogik-vdevice ERROR ### Updating Sensor 'virtual_binary' / id '587' with value '1' for device 'XXXXX couché': Not a boolean !
> <tikismoke> 2017-02-02 19:54:25,052 domogik-vdevice INFO Reply to command 0MQ
> <tikismoke> pourtant c'est bien un dt_bool
> <tikismoke> pourtant depuis domodroid (donc via rest on a ça comme info dans les logs:
> <tikismoke> 2017-02-02 19:57:20,691 domogik-vdevice INFO ==> Received 0MQ messages data: {u'command_id': 178, u'value': u'1', u'device_id': 245}
> <tikismoke> la seule différence c'est value = '1' ou u'1' depuis rest
> <tikismoke> en gros le message MQ est différent s'il viens de REST ou de domoweb

**Comment by fritz-smh** [comment]
Oui, dans un cas on envoie '1' (string), dans l'autre 1 (chiffre)

**Comment by vdomos** [comment]
"un cas on envoie '1' (string), dans l'autre 1 (chiffre)"
et cela va rester dans l'état ou il y a une correction de prévu pour
harmoniser ?

il faut en tenir compte dans les plugins.
J'avais ajouter un controle dans vdevice, justement pour eviter de recevoir
une chaine pour un vdevice de type bool ou number


2017-02-03 9:38 GMT+01:00 Fritz SMH <notifications@github.com>:
