### ISSUE TITLE
Sections : when there is only one section and we click on it, nothing happens

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domoweb#14]
When there is only one section and we click on it, nothing happens. This is "normal" as here is only one section, but this is very disturbin for the user.
Can we at least display the circle of the unique section as we do when there are 2, 3 or more ?

**Comment by ferllings** [comment]
You should see at least the 'root' section, so this is a bug

**Comment by ferllings** [comment]
Fixed in 73d73db4b464bd08f51266ccce99ab7ebd4a4f80
