### ISSUE TITLE
Windows Checkout error

### ISSUE THREAD

**Issue by overload08** [domogik/domoweb#145]
On checkout : 

error: unable to create file packs/widgets/highcharts/Highcharts-4.1.8/exporting-server/java/highcharts-export/highcharts-export-web/target/highcharts-export-web/WEB-INF/classes/com/highcharts/export/controller/ExportController.class: **Filename too long**
error: unable to create file packs/widgets/highcharts/Highcharts-4.1.8/exporting-server/java/highcharts-export/highcharts-export-web/target/highcharts-export-web/WEB-INF/classes/com/highcharts/export/controller/ZeroRequestParameterException.class: **Filename too long**
error: unable to create file packs/widgets/highcharts/Highcharts-4.1.8/exporting-server/java/highcharts-export/highcharts-export-web/target/highcharts-export-web/WEB-INF/classes/com/highcharts/export/interceptor/RequestInterceptor.class: **Filename too long**
Checking out files: 100% (3207/3207), done.
Your branch is up-to-date with 'origin/master'.

**Comment by fritz-smh** [comment]
Hello,

What is the length of your Domoweb git repo path ?
For example : /opt/domoweb =>12

**Comment by overload08** [comment]
/opt/dmg/domoweb => 16

**Comment by overload08** [comment]
57...

I'll try in root directly

**Comment by fritz-smh** [comment]
Avoid the root directory.

I pushed a commit where I deleted these useless files
