### ISSUE TITLE
Domoweb et Chrome 72 

### ISSUE THREAD

**Issue by FrancoisGin28** [domogik/domoweb#162]
Bonjour

Après une install propre de domogik et domoweb 5.2 tout est OK sous Firefox 
mais sous Chrome 72 j'ai juste l'entourage des widgets affiché et rien d'autre ...
Le majordome ne fonctionne plus du tout !

merci d'avance
Francois

**Comment by Nico0084** [comment]
Salut,
Domoweb 0.5.2 utilise Polymer 0.7 et Chrome 72 ne support plus cette version, ils suppriment tous les éléments le supportant.
https://www.polymer-project.org/blog/2018-10-02-webcomponents-v0-deprecations

Bref les seules solutions sont soit de dégrader la version de Chrome soit de passer à la version develop (0.6.0) de domoweb, qui au passage est stable.
Il est fortement conseillé de passer à domogik develop (0.6.0), stable aussi.
Domoweb 0.6 avec  domogik 0.5.2 n'a pas été testé, je crois.

Désolé pour le désagrément.
