### ISSUE TITLE
Grid : 100%cpu used by ff for a new section

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domoweb#19]
browser : ff 31.5.3
I created a new section, go to the configure screen and set:
- Width/Height + Widget size
- w = 600, h = 600, widget size = 100

I added a widget, it is places in the top left corner (no margin at all). When I try to move it, ff goes crazy : 100% cpu and finally ask me if I want to stop the script. After the widget have moved and we see an error (see screenshot)
![cpu](https://cloud.githubusercontent.com/assets/4557426/8532766/dd9002ae-2430-11e5-82b7-7fb50f6e05b8.png)

**Comment by ferllings** [comment]
The problem comes from a miss-understanding of the height/width.
What is asked is a number of rows/columns. So 600 rows*600 columns is too much to handle for your cpu.

Is it better if I rename it to rows/columns? or do you think something else might help?

**Comment by fritz-smh** [comment]
Yes, this would be better
And also add a help picture with the values

4x3 :
+-+-+-+
+-+-+-+
+-+-+-+
