### ISSUE TITLE
sections : when renaming a section with a lot of widget, most of them disappeared

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domoweb#28]
Only the ones in the top left corner were kept... I think this is linked to the grid options

**Comment by fritz-smh** [comment]
Message personnel : et j'avais passé 3 plombes à peaufiner cet écran
GRRRRR ;)

**Comment by ferllings** [comment]
Correct, there is a function that removes all the widgets out of screen, when the grid size has changed.
The issue is probably there.

**Comment by ferllings** [comment]
I can't reproduce it

**Comment by ferllings** [comment]
I disabled it for now until a found a better way (commit 250aa6947d3a9c4dec15ead19a910bd64433b7b3)

**Comment by fritz-smh** [comment]
Seems ok now. Closing
