### ISSUE TITLE
Update to Polymer 1.0

### ISSUE THREAD

**Issue by ferllings** [domogik/domoweb#30]
Polymer supports the extends keyword as in 0.5, but at this point you can only extend built-in DOM elements, such as <button>. For more information, see Inheritance.
https://www.polymer-project.org/1.0/docs/migration.html#inheritance

Workaround? https://www.polymer-project.org/1.0/docs/devguide/behaviors.html

**Comment by Nico0084** [comment]
No more interest, up to polymer 2.1 ->branch polymer2
