### ISSUE TITLE
Permission denied: '/var/lock/domogik/config-mq.lock'

### ISSUE THREAD

**Issue by ferllings** [domogik/domoweb#50]
Problème de droit en lançant domoweb

Traceback (most recent call last):
File "/opt/dmg/domoweb/Domoweb.py", line 14, in <module>
from domoweb.loaders import packLoader, mqDataLoader
File "/opt/dmg/domoweb/domoweb/loaders.py", line 15, in <module>
cli = MQSyncReq(zmq.Context())
File "/opt/dmg/domogik-mq/src/domogikmq/reqrep/client.py", line 60, in init
cfg = Loader('mq').load()
File "/opt/dmg/domogik-mq/src/domogikmq/configloader.py", line 93, in load
file = open(LOCK_FILE, "r+")
IOError: [Errno 13] Permission denied: '/var/lock/domogik/config-mq.lock'

rwx----- 1 domogik nogroup 0 févr. 8 22:45 /var/lock/domogik/config-mq.lock

# History

## 1 Updated by fritz_smh 8 months ago

Tu as trouvé l'origine ?

## 2 Updated by Overload 8 months ago

Nop, j'ai fais un gros chmod 777 /var/lock/domogik/config-mq.lock pour solutionner temporairement le problème.
Bourrin mais efficace.

## 3 Updated by CaraGk 34 minutes ago

J'ai le même bug qui me paraît logique puisque DomoWeb, lancé par défaut avec l'utilisateur domoweb, ne doit pas pouvoir lire le fichier lock de Domogik, lancé avec l'utilisateur domogik.

J'ai testé en lançant DomoWeb avec l'utilisateur domogik, on lève l'erreur du système de fichier.
La vrai question, c'est : pourquoi DomoWeb a-t-il besoin d'accéder au fichier config-mq.lock autrement qu'en lecture seule ?
Si c'est indispensable, ça remet en question l'isolation des deux services avec deux utilisateurs différents, qui pourtant semble une bonne chose de prime abord.
Si non, il faut contourner le problème.

## 4 Updated by CaraGk 10 minutes ago

J'ai résolu en ajoutant l'utilisateur domoweb au group domogik et en ayant :
rw-r--r- 1 domogik domogik 0 oct. 14 11:59 config-mq.lock

## 5 Updated by CaraGk 6 minutes ago

Plutôt :
rw-rw-r- 1 domogik domogik 0 oct. 14 11:59 config-mq.lock

**Comment by Cereal2nd** [comment]
the problem is in the domogik configloader

as this sytem is using a simple read/write mechanisme to handle the lockfile, thats why this sytem tries to write to the file, instead of just read

i start to think we don't need the lockfile at all, after all only the install scripts need to write to the config file, the other scripts only read ...
