### ISSUE TITLE
No rounding value in sensor widgets

### ISSUE THREAD

**Issue by vdomos** [domogik/domoweb#52]
Hello,

This 2 types widgets does not rounding the value of the sensor like this.

![domoweb_widget_temp_2](https://cloud.githubusercontent.com/assets/1257481/10651577/9067e87e-7850-11e5-8502-a691d297c03d.png)

**Comment by fritz-smh** [comment]
Still the case ?

**Comment by vdomos** [comment]
In Domoweb, yes still there.

![domoweb_sensor_rounding_1](https://cloud.githubusercontent.com/assets/1257481/14834259/bd6b5422-0c03-11e6-9ef8-b0aa015c805c.jpg)


I use formula in admin interface for rounding value, if necessary

**Comment by Nico0084** [comment]
Polymer2:  an option precision parameter was added.
