### ISSUE TITLE
Some widgets image missing in Select Widget page

### ISSUE THREAD

**Issue by vdomos** [domogik/domoweb#58]
Hi,
For Fritz
Just so you know,
Widget image for "Phone Calls" and "Sensor string" are missing in "Select Widget" page:

![domoweb_widgets_list_1](https://cloud.githubusercontent.com/assets/1257481/11934142/7b9ae704-a800-11e5-8fe8-11ef4359c527.png)

**Comment by fritz-smh** [comment]
Hi, I was aware of this ;)
I just wanted the develop branch ready to be released before starting to add the screenshots
