### ISSUE TITLE
RINOR: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by jcdutton** [domogik/domoweb#59]
Check domoweb 0.3.1
When in the web admin interface:
http://127.0.0.1:40404/admin
The ERROR message appears:
RINOR: 'NoneType' object is not callable

This renders the admin interface un-usable.
Python 2.7.6
Ubuntu 14.04.3 LTS

What do I need to do to fix this?
How do I get a stack trace instead of a single line message in the web interface?

**Comment by fritz-smh** [comment]
Hi,

Can you please give more details ? You speak of both domoweb and domogik admin

And yoy say you are using 0.3.1 release. The latest release is 0.4.2.

**Comment by jcdutton** [comment]
I am using domogik 0.3.1 and domoweb 0.3.1
I have a plugin that is written for 0.3.1 so I cannot upgrade to 0.4.2 yet.
The error appears to be something wrong with tastypie. The tastypie api appears to have changed.
Do you have any idea what I should change in domoweb 0.3.1 in order to adjust it to the newer tastypie?
I am sure this is a quick fix.
Eventually, I will migrate my plugin to 0.4.2, but I need to get 0.3.1 working again first.

**Comment by fritz-smh** [comment]
Hi,

No idea... could you pass on irc channel and maybe ask to ferllings ? If he
have some time maybe he could help you...

++
Fritz

**Comment by jcdutton** [comment]
I found the answer. To run domogik 0.3.1 you need to force downgrade the following python packages
pip install South==1.0.2
pip install django_tastypie==0.9.11
pip install django==1.4
pip install django_tables2==1.0.4
