### ISSUE TITLE
Text size in Sensor String widget

### ISSUE THREAD

**Issue by vdomos** [domogik/domoweb#65]
Hello

I have a string sensor with few lines like this:

    De 16h05 à 16h10 : Précipitations faibles
    De 16h10 à 16h20 : Pas de précipitations
    De 16h20 à 16h30 : Précipitations modérées
    De 16h30 à 17h05 : Pas de précipitations

But the sensor string widget only display that:

![domoweb_string_sensor](https://cloud.githubusercontent.com/assets/1257481/14530870/2dd45f5e-025b-11e6-9782-5ebd6be7ae9f.jpg)

Possible to auto adjust the text size and "newline" to display properly in the widget ?

thanks,

**Comment by fritz-smh** [comment]
Hi,

I was not very happy with auto adjust or newline when I tested them in this
widget.
Often the result was not really fine...

For your need I think that a new widget would be more approriate.

Something multine line, with a lower font size and surely in another size
(2x3 maybe ?)

Is each line a new value ? Or are all the lines the same value ?

++

**Comment by vdomos** [comment]
It's rain forecast for the next hour, it may be 1 up to 12 lines max if rainfall change every 5mn (never seen).
All lines will be in the format:

De xxhxx à xxhxx : niveau de pluie

niveau de Pluie:
 "Données indisponibles"
 "Pas de précipitations"
 "Précipitations faibles"
 "Précipitations modérées"
 "Précipitations fortes"

**Comment by fritz-smh** [comment]
OK..
Can you on your side try to create the new widget ? I could assist you if
needed.
This is not a very hard to do, basically a copy of the current one with a
different layout and no string shortening process

**Comment by vdomos** [comment]
With only this files to modify/copy ?

./packs/widgets/basic/info.json
./packs/widgets/basic/sensorString.html
./packs/widgets/basic/sensorString.png

**Comment by fritz-smh** [comment]
info.json  : duplicate the sensorString part and rename the new one as
"sensorStringMultiline" for example. In it you can also choose the display
size.
sensorString.html : copy it as the same name you defined in the json and
replace in it all sensorString by the new name.
png file : you will create it when the widget will be ok

Warning :
- An update of info.json imply a domoweb restart
- If you change a widget size during the dev, you should before delete the
old one.

**Comment by vdomos** [comment]
ok, I will test that.
thanks

**Comment by fritz-smh** [comment]
Closing as you did a multiline widgte
