### ISSUE TITLE
[develop] Domoweb won't start

### ISSUE THREAD

**Issue by overload08** [domogik/domoweb#72]
When i do /etc/init.d/domoweb start : 

 * Starting DomoWeb...
   Checking if Domogik is available (10.0.101.25:40405) ...................................................................................................................................................................................................................................................

and Domoweb doesn't start.

It's ok when i launch Domoweb.py manualy.

**Comment by fritz-smh** [comment]
Can you give us the domoweb logs ?

**Comment by overload08** [comment]
domoweb.log is empty

**Comment by overload08** [comment]
I am seeing something...

That's domogik the problem, not domoweb!
If domogik doesn't start, domoweb too.

I have opened a ticket for domogik problem

**Comment by overload08** [comment]
It's ok
