### ISSUE TITLE
First widget is not editable

### ISSUE THREAD

**Issue by titoko** [domogik/domoweb#81]
https://github.com/domogik/domoweb/blob/develop/static/js/main.js#L130
need to set this to id+1 in order to have a z index starting to 2
because body;after is set to z-index=1
https://github.com/domogik/domoweb/blob/develop/templates/base.html#L34

**Comment by fritz-smh** [comment]
It must be related to one recent pull request which changes the way to
handle index.
Thanks to point this one !
I will fix and push with other things in the next days.

**Comment by titoko** [comment]
Work for me, closing this !
